### ISSUE TITLE
Bonus maps enhancements

### ISSUE THREAD

**Issue by Luke18033** [Joshua-Ashton/HL2-GamepadUI#2]
The current gamepad UI bonus maps dialog works for what vanilla Portal does, but for mods it is somewhat lacking compared to the original GameUI version.
- It doesn't support scrolling, so you can only have 6 items per folder before they start to extend offscreen (though are still selectable). Some mods such as Entropy: Zero 2 have more than 6 items in a single folder.
- The "comment" line from the bonus map definitions isn't shown anywhere. Some mods such as Rexaura use this to explain how to unlock secret maps, so without it the player is left clueless as to how these maps are unlocked.
- Locked maps can't be highlighted, which goes alongside the problem above in preventing players from viewing details of locked maps.

**Comment by DasMaddi** [comment]
Bonus maps UI may need to stay as-is with this repo unfortunately, if I recall correctly, it was #if'd out due to being un-compilable on public code for SDK2013, due to missing definitions for the score-keeping functions. 

I believe the only way to compile it is from using other versions of GameUI that have slipped out over the years, and unfortunately we are not able to implement that here.

**Comment by Luke18033** [comment]
Well, it'd still be nice to have if these changes ever get pushed to the Portal/HL2 versions. Could maybe add #ifdefs so the bonus maps setting only works if the bonus maps menu is actually compiled in.

**Comment by DasMaddi** [comment]
Perhaps so, but for now, I am closing this.
